add support for specifying GOOS GOARCH and version

diff --git a/upgrade_go b/upgrade_go
--- a/upgrade_go
+++ b/upgrade_go
@@ -1,13 +1,105 @@
 #!/bin/bash
 # upgrade to current version
+version="1.7.4"
+goarch="amd64"
+goos="linux"
+
+valid=(
+	"darwin:386"
+	"darwin:amd64"
+	"freebsd:386"
+	"freebsd:amd64"
+	"linux:386"
+	"linux:amd64"
+	"linux:armv6l"
+	"linux:ppc64le"
+	"linux:390x"
+	)
+
+while [[ $# > 0 ]]
+do
+	case "$1" in
+		-h|--help)
+			echo ""
+			echo "Usage: ./upgrade_go [OPTIONS]"
+			echo ""
+			echo "  Use when Go is already installed and you wish to install a different version"
+			echo "  The default workspace location is $HOME/go"
+			echo "  The default os is $goos"
+			echo "  The default arch is $goarch"
+			echo "  The default version is $version"
+			echo ""
+			echo "  OPTIONS:"
+			echo "  -h, --help               print help message"
+			echo "  -w, --workspace          specify a custom workspace (\$GOPATH)"
+			echo "  -a, --arch, --goarch     specify the arch (\$GOARCH)"
+			echo "  -o, --os, --goos         specify the os (\$GOOS)"
+			echo "  -v, --version            specify the version"
+			echo ""
+
+			exit 0
+			;;
+		-w|--workspace)
+			workspace="$2"
+			shift
+			;;
+		-a|--goarch|--arch)
+			goarch="$2"
+			shift
+			;;
+		-o|--os|--goos)
+			goos="$2"
+			shift
+			;;
+		-v|--version)
+			version="$2"
+			shift
+			;;
+	esac
+shift
+done
+
+
+# see if it's a valid combination.
+osarch=$goos$goarch
+
+for v in "${valid[@]}"
+do
+	if [ "$v" = "$osarch" ] ; then
+		isvalid=true
+		break
+	fi
+done
+
+# if it was an invalid combination; return a message letting them know
+if ! $isvalid; then
+	echo "invalid GOOS GOARCH combination: $goos $goarch"
+	echo "supported GOOS GOARCH combinations:"
+	for v in "${valid[@]}"
+	do
+		if [ "$v" = "linux:amd64" ]; then
+			echo "     $v (default)"
+		else
+			echo "     $v"
+		fi
+	done
+	 exit 1
+fi
+
+# everything is ok
+# first download
+# download and extract Go to /usr/local/go/
+wget_output=$(wget -O /tmp/go.$version.tar.gz https://storage.googleapis.com/golang/go$version.$goos-$goarch.tar.gz)
+if [ $? -ne 0 ]; then
+	echo "unable to install go $version"
+	exit 1
+fi
 
 # remove the old Go
 sudo rm -rf /usr/local/go
 
+sudo tar xzf /tmp/go$.$version.tar.gz /usr/local
+
 # remove artifacts from prior version
 # May not be necessary: commentint out for now
 rm -rf $GOPATH/pkg/*
-
-# download and extract Go to /usr/local/go/
-# change the tarball for different version/arch
-wget -qO- https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz | sudo tar xz -C /usr/local
